services:
  go-backend:
    build: 
      context: ./go-backend
      dockerfile: Dockerfile
    container_name: go-backend
    # command: tail -f /dev/null
    depends_on:
      - postgres-db
    env_file:
      - ./go-backend/.env
    ports:
      - "8080:8080"
    networks:
      - shop_app_network

  postgres-db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go_backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shop_app_network

networks:
  shop_app_network:

volumes:
  pgdata:
