version: '3.8'

services:
  go-backend:
    build: .
    container_name: go-backend
    depends_on:
      - postgres-db
    env_file:
      - ./go_backend/.env
    ports:
      - "8080:8080"
    networks:
      - inventory_app_network

  postgres-db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go_backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inventory_app_network

networks:
  inventory_app_network:

volumes:
  pgdata:
